# Javascript 비동기 처리

## 비동기 처리

![그림1](https://user-images.githubusercontent.com/38815618/88607305-dcca6400-d0b9-11ea-9701-c0fc59732e96.jpg)

- 동기(Synchronous)적 처리: 요청을 보낸 후 해당 요청의 응답을 받아야 다음 동작을 실행하는 방식
- 비동기(Asynchronous)적 처리: 요청을 보낸 후 응답과 관계없이 다음 동작을 실행하는 방식

> Node.js는 싱글 스레드이며, 이벤트를 처리하는 콜 스택이 하나이다. 따라서 여러가지 이벤트를 처리할 때 동기적으로 처리하게 된다면 하나의 이벤트가 모두 처리될 때까지 다른 어떤 이벤트도 수행하지 못하는 현상이 발생한다. 자바스크립트는 즉시 처리하지 못하는 이벤트들을 백그라운드로 보내고 일련의 동작 후에 태스크 큐로 보낸다. 이벤트 루프는 정해진 규칙에 따라 콜백 함수를 호출 스택으로 부른다.

### 사례) Jquery ajax 통신

```javascript
function getData () {
    var tableData;
    $.get('https://domain.com/products/1', function(response) {
        tableData = response;
    });
    return tableData;
}

console.log(getData()); // undefined
```

<p>
    위 코드에서 $.get()이 ajax 통신을 하는 부분이다. https://domain.com 에다가 HTTP GET 요청을 날려 1번 상품(product) 정보를 요청한다. 즉, 지정된 URL에 ‘데이터를 하나 보내주세요’ 라는 요청을 날리는 것과 같다. $.get()로 데이터를 요청하고 받아올 때까지 기다려주지 않고 return tableData를 실행했기 때문에, getData()의 결과 값은 초기 값을 설정하지 않은 tableData의 값 undefined를 출력한다.
</p>

### 사례) setTimeout()

```javascript
console.log('hello');
setTimeout(function() {
    console.log('bye')
}, 3000);
console.log('hello again');

// hello
// hello again
// bye
```

<p>
    setTimeout()은 Web API의 한 종류이다. 코드를 바로 실행하지 않고 지정한 시간만큼 기다렸다가 로직을 실행한다. setTimeout() 역시 비동기 방식으로 실행되기 때문에 3초를 기다렸다가 다음 코드를 수행하는 것이 아니라 일단 setTimeout()을 실행하고 나서 바로 다음 코드인 console.log('hello again')으로 넘어간다.
</p>

## 콜백 함수

```javascript
function getData(callbackFunc) {
    $.get('https://domain.com/products/1', function (response) {
        callbackFunc(response); // 서버에서 받은 데이터 response를 callbackFunc() 함수에 넘겨줌
    });
}

getData(function(tableData) {
    console.log(tableData); // $.get()의 response 값이 tableData에 전달됨
});
```

<p>
    앞서 비동기 처리 방식에 의해 야기될 수 있는 문제들을 해결하기 위에 콜백(callback) 함수를 사용한다. 위의 예시는 앞에서 살펴본 ajax 통신 코드를 콜백 함수로 개선한 것이다.
</p>

### 콜백 지옥

```javascript
$.get('url', function(response) {
    parseValue(response, function(id) {
        auth(id, function(result) {
            display(result, function(text) {
                console.log(text);
            });
        });
    });
});
```

<p>
    웹 서비스를 개발하다 보면 서버에서 데이터를 받아와 화면에 표시하기까지 인코딩, 사용자 인증 등을 처리해야 하는 경우가 있다. 만약 이 모든 과정을 비동기로 처리해야 한다고 하면 위와 같이 콜백 안에 콜백을 계속 무는 형식으로 코딩을 하게 된다. 이러한 코드 구조는 가독성도 떨어지고 로직을 변경하기도 어려우며, 이를 콜백 지옥이라고 한다.
</p>

```javascript
function parseValueDone(id) {
    auth(id, authDone);
}
function authDone(result) {
    display(result, authDone);
}
function displayDone(text) {
    console.log(text);
}
$.get('url', function(response) {
    parseValue(response, parseValueDone)
});
```

<p>
    만약 코딩 패턴으로만 콜백 지옥을 해결하려면 위 예시와 같이 각 콜백 함수를 분리해주면 된다. 중첩해서 선언했던 콜백 익명 함수를 각각의 함수로 구분한다.
</p>

<p>
    정리된 코드를 간단하게 살펴보면 먼저, ajax 통신으로 받은 데이터를 parseValue() 메서드로 파싱 한다. parseValueDone()에 파싱 한 결과값인 id가 전달되고 auth() 메서드가 실행된다. auth() 메서드로 인증을 거치고 나면 콜백 함수 authDone()이 실행된다. 인증 결과 값인 result로 display()를 호출하면 마지막으로 displayDone() 메서드가 수행되면서 text가 콘솔에 출력된다.
</p>

## Promise

![그림2](https://user-images.githubusercontent.com/38815618/88607310-ddfb9100-d0b9-11ea-95de-b6170ad899b3.png)

- 프로미스는 자바스크립트 비동기 처리에 사용되는 객체이다.
- 프로미스 3가지 상태
  - **Pending(대기)**: 비동기 처리 로직이 아직 완료되지 않은 상태
  - **Fulfilled(이행)**: 비동기 처리가 완료되어 프로미스가 결과 값을 반환해준 상태
  - **Rejected(실패)**: 비동기 처리가 실패하거나 오류가 발생한 상태

### Pending(대기)

```javascript
new Promise(function(resolve, reject) {
    //...
});
```

- new Promise() 메서드를 호출하면 대기(Pending) 상태가 된다.
- 메서드를 호출할 때 콜백 함수를 선언할 수 있고, 콜백 함수의 인자는 resolve, reject이다.

### Fulfilled(이행)

```javascript
function getData(callback) {
    return new Promise(function(resolve, reject) {
        var data = 100;
        resolve(data);
    });
}

getData().then(function(resolveData) {
    console.log(resolveData); // 100
});
```

- 콜백 함수의 인자 resolve를 아래와 같이 실행하면 이행(Fulfilled) 상태가 된다.
- 이행 상태가 되면 아래와 같이 then()을 이용하여 처리 결과 값을 받을 수 있다.

### Rejected(실패)

```javascript
function getData(callback) {
    return new Promise(function(resolve, reject) {
        reject(new Error('Request is failed'));
    });
}

getData().then().catch(function(err) {
    console.log(err); // Error: Request is failed
})
```

- reject를 호출하면 실패(Rejected) 상태가 된다.
- 실패 상태가 되면 실패한 이유(실패 처리의 결과 값)를 catch()로 받을 수 있다.

### ajax 통신 예제

```javascript
function getData(callback) {
    return new Promise(function(resolve, reject) {
        $.get('url', function(response) {
            if (response) {
                resolve(response);
            };
            reject(new Error('Request is failed'));
        });
    });
}

// $.get() 결과에 따라 response 또는 error 출력
getData()
    .then(function(data) {
        console.log(data);
    }).catch(function(err) {
        console.error(err);
    });
```

- 서버에서 제대로 응답을 받아오면 resolve() 메서드를 호출하고, 응답이 없으면 reject() 메서드를 호출한다.
- 호출된 메서드에 따라 then()이나 catch()로 분기하여 응답 결과 또는 오류를 출력합니다.

### 에러 처리

```javascript
// 두 번째 인자를 이용하여 에러 처리
getData().then(
    handleSuccess,
    handleError
);

// catch()를 이용하여 에러 처리
getData().then().catch();
```

- 에러처리는 then()의 두 번째 인자로 에러를 처리하는 방법, catch()를 이용하는 방법 2가지가 있다.
- 첫 번째 방법은 then()의 첫 번째 콜백 함수 내부에서 오류가 나는 경우 오류를 제대로 잡지 못한다.
- 가급적이면 catch()를 사용하여 처리하는 방법을 권장한다.

## async와 await

<p>
    async와 await는 자바스크립트의 비동기 처리 패턴 중 최근에 나온 문법이며, 기존의 콜백 함수와 프로미스의 단점을 보완하고 개발자가 읽기 좋은 코드를 작성하게 도와준다.
</p>

```javascript
// 기본 문법
async function 함수명() {
    await 비동기_처리_메소드_명();
}
```

<p>
    함수 앞에 async라는 예약어를 붙이고, 함수의 내부 로직 중 HTTP 통신을 하는 비동기 처리 코드 앞에 await를 붙인다. 비동기 처리 메서드가 반드시 프로미스 객체를 반환해야 await가 의도한 대로 동작한다.
</p>

### 간단 예제

```javascript
function fetchItems() {
    return new Promise(function(resolve, reject) {
        var items = [1, 2, 3];
        resolve(items);
    });
}

async function logItems() {
    var resultItmes = await fetchItmes();
    console.log(resultItmes); // [1, 2, 3]
}
```

1. 먼저 fetchItems() 함수는 프로미스 객체를 반환하는 함수이다.
2. 프로미스는 자바스크립트 비동기 처리를 위한 객체이다.
3. fetchItems() 함수를 실행하면 프로미스가 이행(Resolved)되며 결과 값은 items 배열이 된다.
4. logItems() 함수를 실행하면 fetchItems() 함수의 결과 값인 items 배열이 resultItems 변수에 담기고, 콘솔에는 [1, 2, 3]이 출력된다.

<p>
    await를 사용하지 않았다면 데이터를 받아온 시점에 콘솔을 출력할 수 있게 콜백 함수나 .then()등을 사용해야 했지만, async await 문법 덕택에 비동기에 대한 사고를 하지 않아도 된다.
</p>

### 예외 처리

```javascript
async function logTodoTitle() {
    try {
        var user = await fetchUser();
        if (user.id === 1) {
            var todo = await fetchTodo();
            console.log(todo.title);
        }
    } catch (error) {
        console.log(error);
    }
}
```

<p>
    async와 await에서 예외 처리는 try catch 방식을 사용한다. 위 예시에서 실행하다가 발생하는 네트워크 통신 오류 뿐만 아니라, 간단한 타입 오류 등의 일반적인 오류까지도 잡아낼 수 있다. 발견된 에러는 error 객체에 담기기 때문에 에러의 유형에 맞게 에러 코드를 처리할 수 있다.
</p>
